// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sme.proto

package com.sme.app.proto;

public interface DepartmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sme.app.proto.Department)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string code = 3;</code>
   * @return The code.
   */
  String getCode();
  /**
   * <code>string code = 3;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();
}
