// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sme.proto

package com.sme.app.proto;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sme.app.proto.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  String getLastName();
  /**
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>double salary = 5;</code>
   * @return The salary.
   */
  double getSalary();

  /**
   * <code>.com.sme.app.proto.Department department = 6;</code>
   * @return Whether the department field is set.
   */
  boolean hasDepartment();
  /**
   * <code>.com.sme.app.proto.Department department = 6;</code>
   * @return The department.
   */
  Department getDepartment();
  /**
   * <code>.com.sme.app.proto.Department department = 6;</code>
   */
  DepartmentOrBuilder getDepartmentOrBuilder();
}
