// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sme.proto

package com.sme.app.proto;

public interface EmployeeListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sme.app.proto.EmployeeList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.sme.app.proto.Employee product = 1;</code>
   */
  java.util.List<Employee>
      getProductList();
  /**
   * <code>repeated .com.sme.app.proto.Employee product = 1;</code>
   */
  Employee getProduct(int index);
  /**
   * <code>repeated .com.sme.app.proto.Employee product = 1;</code>
   */
  int getProductCount();
  /**
   * <code>repeated .com.sme.app.proto.Employee product = 1;</code>
   */
  java.util.List<? extends EmployeeOrBuilder>
      getProductOrBuilderList();
  /**
   * <code>repeated .com.sme.app.proto.Employee product = 1;</code>
   */
  EmployeeOrBuilder getProductOrBuilder(
      int index);
}
