// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sme.proto

package com.sme.app.proto;

public final class Sme {
  private Sme() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sme_app_proto_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sme_app_proto_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sme_app_proto_EmployeeList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sme_app_proto_EmployeeList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sme_app_proto_Department_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sme_app_proto_Department_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tsme.proto\022\021com.sme.app.proto\"\217\001\n\010Emplo" +
      "yee\022\n\n\002id\030\001 \001(\005\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tl" +
      "ast_name\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\016\n\006salary\030" +
      "\005 \001(\001\0221\n\ndepartment\030\006 \001(\0132\035.com.sme.app." +
      "proto.Department\"<\n\014EmployeeList\022,\n\007prod" +
      "uct\030\001 \003(\0132\033.com.sme.app.proto.Employee\"4" +
      "\n\nDepartment\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\014" +
      "\n\004code\030\003 \001(\t2\222\002\n\017EmployeeService\022M\n\017getE" +
      "mployeeById\022\033.com.sme.app.proto.Employee" +
      "\032\033.com.sme.app.proto.Employee\"\000\022P\n\022getEm" +
      "ployeeByEmail\022\033.com.sme.app.proto.Employ" +
      "ee\032\033.com.sme.app.proto.Employee\"\000\022^\n\032get" +
      "EmployeesByDepartmentId\022\035.com.sme.app.pr" +
      "oto.Department\032\037.com.sme.app.proto.Emplo" +
      "yeeList\"\000B\025\n\021com.sme.app.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sme_app_proto_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sme_app_proto_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sme_app_proto_Employee_descriptor,
        new String[] { "Id", "FirstName", "LastName", "Email", "Salary", "Department", });
    internal_static_com_sme_app_proto_EmployeeList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sme_app_proto_EmployeeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sme_app_proto_EmployeeList_descriptor,
        new String[] { "Product", });
    internal_static_com_sme_app_proto_Department_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_sme_app_proto_Department_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sme_app_proto_Department_descriptor,
        new String[] { "Id", "Name", "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
